node {
    try {
        stage ('Jenkins Jobs Triggered'){
            echo "Pipeline Start ..."
        }
        
        stage('Get Source from SCM') {
            stage = 'Get Source from SCM'
            git branch: "master",
            credentialsId: 'kurnia_akbari',
            url: 'https://github.com/KURNIA-AKBARI/testing-apps.git'
            
        }
        stage('Create Docker Containers') {
            stage = 'Create Docker Containers'
		dir ('nginx-wayae'){
                script {
          sh "docker -v"
                    sh "pwd"
          sh "docker build --network host -t kurniaakbarialdianza/testerapps:alpha ."                    
        	}
      	}
    }
	     stage('Push Registry') {
		     stage = 'Push Registry'
		dir ('nginx-wayae'){
                script {
	    docker.withRegistry('registry.hub.docker.com', 'dockeruser') {
                    sh "docker push kurniaakbarialdianza/testerapps:alpha"     
		    }
		}
		}
	     }
    stage ('Deploy to Kubernetes'){
            stage = 'Deploy to Kubernetes'
	    dir ('nginx-wayae'){
            script {
        withKubeConfig(credentialsId: 'cluster_w', serverUrl: 'https://192.168.100.130:6443'){
          sh 'kubectl apply -f deployment-nginx.yaml'
                    sh 'kubectl apply -f service-nginx.yaml'
                    sh 'kubectl apply -f ingress-nginx.yaml'
                }
	    }
            }
    }
				
		stage ('Notification') {
			stage = 'Notification'
			sh "curl -s -X POST https://api.telegram.org/bot702898762:AAGrLYF_keCzywv9nLMAwoxaOedXrH1ZdoE/sendMessage -d chat_id=-457152037 -d text='Deployment ${env.JOB_NAME} Berhasil'"
		}
	}
		catch (e) {
			sh "curl -s -X POST https://api.telegram.org/bot702898762:AAGrLYF_keCzywv9nLMAwoxaOedXrH1ZdoE/sendMessage -d chat_id=-457152037 -d text='Deployment ${env.JOB_NAME} Gagal Pada Stage ${stage}'"
    	}
    }
